### ISSUE TITLE
Unicode error color

### ISSUE THREAD

**Issue by h3st** [mcmaniac/npaste.de#3]
Definitions get an error color in haskell if they contain unicode, even though that's fine.

http://npaste.de/p/hwI/

**Comment by mcmaniac** [comment]
Related to the [highlighter package](http://hackage.haskell.org/package/highlighter), not directly npaste…

**Comment by h3st** [comment]
Looks like [the lexer](http://hackage.haskell.org/package/highlighter-0.2.2/docs/src/Text-Highlighter-Lexers-Haskell.html#lexer) is based on regexes. I thought Haskell was all fancy with Parsec and stuff?

```haskell
all isAlphaNum "løk"
True```

oh well

**Comment by mcmaniac** [comment]
There really is no alternative highlighter that I know of that doesn't use regexp…

**Comment by h3st** [comment]
ISAGN

**Comment by mcmaniac** [comment]
OFPR liksom
